image: ubuntu #name of image to run the build against
#run_params: "-e PASSWORD=moew"  
command:
  - apt-get update
  - apt-get install htop -y
#links: #links to parent image using docker links
#  - image: redis
#    name: content-uat4 #optional; defaults to image name
#    run_params: "-v `pwd`:/content" #optional run params
#    links: # Links to parent container; links can be nested indefinitely
#      - image: mysql
