FORMAT: 1A
HOST: http://www.google.com

# Hosted Puppetmaster API
Puppetmaster API is a hosted puppet master service. Currently 100% POC, nothing usable.


# Group Master Management
Create, destroy, and manage puppet masters

## Puppet Masters [/master]
List or create puppet masters

### List all masters [GET]
+ Response 200 (application/json)

        [{
          "uuid": "34378253-2009-4085-a687-8252a8d0014d",
          "fqdn": "mymaster.example.com",
          "status": "running"
        }, {
          "uuid": "ee03ffd8-2c65-4fa3-9309-fdbe64afa84f",
          "fqdn": "testbox.dev.example.com",
          "status": "provisioning"
        }, {
          "uuid": "413f77df-9568-49b3-9e29-f65016b0b524",
          "fqdn": "connor.example.com",
          "status": "destroyed"
        }]

### Create a master [POST]
Asynchronous creation; queues master for creation. May take several minutes to actually provision the master.

+ Request (application/json)

        {
          "fqdn": "production.example.com",
          "gitrepo": "https://github.com/githubtraining/hellogitworld.git"
        }

+ Response 201 (application/json)

        { 
          "uuid": "193627c9-eb95-417b-bc59-5ae69b0dd146",
          "fqdn": "production.example.com",
          "gitrepo": "https://github.com/githubtraining/hellogitworld.git",
          "status": "provisioning"
        }

## Management [/master/{uuid}]
Get and set information about a given master

+ Parameters
    + uuid (required, string, `c9bb1af2-081a-4a3a-8f90-d1ad0e7e7c33`) ... String `uuid` of the master. Has example value.

### Get information about a master [GET]
Date fields are in RFC 2822 format.
+ Response 200 (application/json)

        { 
          "uuid": "193627c9-eb95-417b-bc59-5ae69b0dd146",
          "created": "Sat, 06 Sep 2014 10:00:22 -0700",
          "fqdn": "puppetmaster.example.com",
          "gitrepo": "https://github.com/githubtraining/hellogitworld.git",
          "status": "running"
        }

### Remove a master [DELETE]
Asynchronous removal; queues master for deletion. May take several minutes to actually destroy the master.

+ Response 202

        { 
          "uuid": "193627c9-eb95-417b-bc59-5ae69b0dd146",
          "created": "Sat, 06 Sep 2014 10:00:22 -0700",
          "destroyed": "Sat, 06 Sep 2014 15:07:18 -0700",
          "fqdn": "puppetmaster.example.com",
          "status": "terminating"
        }

## List Provisioning Keys [/master/{uuid}/keys]
Access all node provisioning keys used to connect client nodes to masters. Secret keys are not visible after creation.

+ Parameters
    + uuid (required, string, `c9bb1af2-081a-4a3a-8f90-d1ad0e7e7c33`) ... String `uuid` of the master. Has example value.

### List node provisioning keys [GET]
+ Response 200 (application/json)

        [{
          "name": "dc1-prod",
          "created": "Sat, 06 Sep 2014 10:00:22 -0700"
        },
        {
          "name": "dc2-prod",
          "created": "Fri, 05 Sep 2014 08:05:02 -0700"
        }]


### Provisioning Keys [/master/{uuid}/keys/{name}]
+ Parameters
    + name (required, string, `dc-west01-prod`) ... name of the provisioning key. Has example value.
    + uuid (required, string, `c9bb1af2-081a-4a3a-8f90-d1ad0e7e7c33`) ... String `uuid` of the master. Has example value.

### Describe a node provisioning key [GET]
+ Response 200 (application/json)

        {
          "name": "dc-west01-prod",
          "created": "Fri, 05 Sep 2014 08:05:02 -0700"
        }

### Create a node provisioning key [POST]

+ Response 201 (application/json)

        {
          "name": "dc3-staging",
          "created": "Fri, 05 Sep 2014 08:05:02 -0700",
          "secret_key": "1k1Z1pT2t3heX939xa7uDE4EeISBL69Z"
        }


### Delete a node provisioning key [DELETE]

+ Response 202 (application/json)

        {
          "name": "dc3-staging",
          "created": "Sat, 06 Sep 2014 10:00:22 -0700",
          "destroyed": "Sat, 06 Sep 2014 15:07:18 -0700"
        }